# Generated by Django 4.2 on 2023-04-16 13:25

from django.db import migrations, models
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrationstaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('designation', models.CharField(blank=True, max_length=128, null=True)),
                ('department', models.CharField(blank=True, max_length=128, null=True)),
                ('image', versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='media/officestaffs/')),
            ],
            options={
                'verbose_name': 'Administrationstaff',
                'verbose_name_plural': 'Administrationstaffs',
            },
        ),
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('dob', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=128, null=True)),
                ('age', models.CharField(blank=True, max_length=128, null=True)),
                ('nationality', models.CharField(blank=True, max_length=128, null=True)),
                ('state', models.CharField(blank=True, max_length=128, null=True)),
                ('father_name', models.CharField(blank=True, max_length=128, null=True)),
                ('father_designation', models.CharField(blank=True, max_length=128, null=True)),
                ('organisation', models.CharField(blank=True, max_length=128, null=True)),
                ('permenent_address', models.TextField()),
                ('pin_number', models.CharField(blank=True, max_length=128, null=True)),
                ('email', models.CharField(max_length=128)),
                ('phone', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': 'web_admission',
                'verbose_name_plural': 'web_admissions',
            },
        ),
        migrations.CreateModel(
            name='FlashNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
            ],
            options={
                'verbose_name': 'web_flash_news',
                'verbose_name_plural': 'web_flash_news',
            },
        ),
        migrations.CreateModel(
            name='Lifeattim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('image', versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='media/')),
            ],
            options={
                'verbose_name': 'web_lifeattim',
                'verbose_name_plural': 'web_lifeattims',
            },
        ),
        migrations.CreateModel(
            name='NewsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('date', models.DateField(blank=True, null=True)),
                ('image', versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='media/')),
            ],
            options={
                'verbose_name': 'web_news_event',
                'verbose_name_plural': 'web_news_events',
            },
        ),
        migrations.CreateModel(
            name='Placement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('designation', models.CharField(max_length=128)),
                ('image', versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='media/')),
            ],
            options={
                'verbose_name': 'web_placement',
                'verbose_name_plural': 'web_placements',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('designation', models.CharField(blank=True, max_length=128, null=True)),
                ('discription', models.TextField(blank=True, null=True)),
                ('image', versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='media/')),
            ],
            options={
                'verbose_name': 'web_tesimonial',
                'verbose_name_plural': 'web_tesimonials',
            },
        ),
    ]
