# Generated by Django 4.2 on 2023-05-27 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_complaint'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('email', models.CharField(blank=True, max_length=128, null=True)),
                ('message', models.TextField()),
            ],
            options={
                'verbose_name': 'web_contact',
                'verbose_name_plural': 'web_contacts',
            },
        ),
    ]
