# Generated by Django 4.2 on 2023-05-29 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_rateus'),
    ]

    operations = [
        migrations.CreateModel(
            name='rate_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(blank=True, max_length=128, null=True)),
                ('feedback', models.CharField(choices=[('star1', 'Star1'), ('star2', 'Star2'), ('star3', 'Star3'), ('star4', 'Star4'), ('star5', 'Star5')], max_length=20)),
            ],
        ),
    ]
