# Generated by Django 4.2 on 2023-05-30 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_rate_us'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rate_us',
            options={'verbose_name': 'web_rateus', 'verbose_name_plural': 'web_rateuss'},
        ),
    ]
