# Generated by Django 4.2 on 2023-06-05 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_ratereview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='rate_us',
        ),
        migrations.DeleteModel(
            name='Rateus',
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
