# Generated by Django 4.2 on 2023-06-10 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_rate_us'),
    ]

    operations = [
        migrations.DeleteModel(
            name='rate_us',
        ),
        migrations.DeleteModel(
            name='Raterev',
        ),
    ]
